version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: posrestaurant_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd! # Pamiętaj, musi spełniać politykę złożoności
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: posrestaurant_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # Port komunikacyjny AMQP
      - "15672:15672" # Panel zarządzania (UI)

volumes:
  sqldata: